project_id = "thizhgarftsbdjywnbzn"

[functions.create-user-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.admin-dashboard]
verify_jwt = true
